title: "Ayush's Blog"
author: "Ayush"
description: "my blog where i share what i am learning and going through while building my startups and a lot of side projects" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "ayushkv10204@gmail.com"
twitter_username: "0xayush1"
github_username: "CrackedResearcher"
linkedin_username: "ayushfrs"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
youtube_username: "Ayush_Chief"
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
